# Author: Aritra Bal
# Date: July 23, 2025
# Configuration file for quantile regression decorrelation project data paths

data:
  # Base path template - XYZ will be replaced with run number
  root_dir: "/storage/9/abal/CASE/VAE_results/events/run_{run_number}/"
  
  # QCD background samples
  qcd_samples:
    - "qcd_data_sideband"
    - "qcd_sig_orig"
    - "qcd_sig_test"
    - "qcd_sig_Test"
    - "qcdSigTestSB"
  
  # Signal samples organized by physics model
  signal_samples:
    # Q* -> QW signals
    qstar_signals:
      - "QstarToQW_M_2000_mW_170"
      - "QstarToQW_M_2000_mW_25"
      - "QstarToQW_M_2000_mW_400"
      - "QstarToQW_M_2000_mW_80"
      - "QstarToQW_M_3000_mW_170"
      - "QstarToQW_M_3000_mW_25"
      - "QstarToQW_M_3000_mW_400"
      - "QstarToQW_M_3000_mW_80"
      - "QstarToQW_M_5000_mW_170"
      - "QstarToQW_M_5000_mW_25"
      - "QstarToQW_M_5000_mW_400"
      - "QstarToQW_M_5000_mW_80"
    
    # RS Graviton signals
    rs_graviton_signals:
      - "RSGravitonToGluonGluon_kMpl01_M_1000"
      - "RSGravitonToGluonGluon_kMpl01_M_2000"
      - "RSGravitonToGluonGluon_kMpl01_M_3000"
      - "RSGravitonToGluonGluon_kMpl01_M_5000"
    
    # W_KK -> W Radion signals
    wkk_radion_signals:
      - "WkkToWRadionToWWW_M2000_Mr170"
      - "WkkToWRadionToWWW_M2000_Mr400"
      - "WkkToWRadionToWWW_M3000_Mr170"
      - "WkkToWRadionToWWW_M3000_Mr400"
      - "WkkToWRadionToWWW_M5000_Mr170"
      - "WkkToWRadionToWWW_M5000_Mr400"
    
    # W' -> B'T signals
    wprime_signals:
      - "WpToBpT_Wp2000_Bp170_Top170_Zbt"
      - "WpToBpT_Wp2000_Bp25_Top170_Zbt"
      - "WpToBpT_Wp2000_Bp400_Top170_Zbt"
      - "WpToBpT_Wp2000_Bp80_Top170_Zbt"
      - "WpToBpT_Wp3000_Bp170_Top170_Zbt"
      - "WpToBpT_Wp3000_Bp25_Top170_Zbt"
      - "WpToBpT_Wp3000_Bp400_Top170_Zbt"
      - "WpToBpT_Wp3000_Bp80_Top170_Zbt"
      - "WpToBpT_Wp5000_Bp170_Top170_Zbt"
      - "WpToBpT_Wp5000_Bp25_Top170_Zbt"
      - "WpToBpT_Wp5000_Bp400_Top170_Zbt"
      - "WpToBpT_Wp5000_Bp80_Top170_Zbt"
    
    # X -> YY' -> 4Q signals
    x_to_yyprime_signals:
      - "XToYYprimeTo4Q_MX2000_MY170_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX2000_MY25_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX2000_MY25_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX2000_MY400_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX2000_MY400_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX2000_MY400_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX2000_MY400_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX2000_MY80_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX2000_MY80_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX2000_MY80_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX3000_MY170_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX3000_MY170_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX3000_MY25_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX3000_MY25_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX3000_MY25_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX3000_MY80_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX3000_MY80_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX3000_MY80_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX5000_MY170_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX5000_MY170_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX5000_MY25_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX5000_MY25_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX5000_MY25_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX5000_MY25_MYprime80_narrow"
      - "XToYYprimeTo4Q_MX5000_MY400_MYprime170_narrow"
      - "XToYYprimeTo4Q_MX5000_MY400_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX5000_MY400_MYprime400_narrow"
      - "XToYYprimeTo4Q_MX5000_MY80_MYprime25_narrow"
      - "XToYYprimeTo4Q_MX5000_MY80_MYprime400_narrow"
    
    # X -> YY' smeared signals (systematic variations)
    x_to_yyprime_smeared_signals:
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow_smear5"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow_smear10"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow_smear20"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow_smear30"
      - "XToYYprimeTo4Q_MX3000_MY400_MYprime400_narrow_smear40"
    
    # Y -> HH signals
    y_to_hh_signals:
      - "YtoHH_Htott_Y2000_H400"
      - "YtoHH_Htott_Y3000_H400"
      - "YtoHH_Htott_Y5000_H400"
    
    # Z' -> T'T' signals
    zprime_signals:
      - "ZpToTpTp_Zp2000_Tp400"

  # File extension settings
  file_settings:
    suffix: "_RECO"  # Added automatically to all sample names
    extension: ".h5"  # Assuming H5 format based on project description
  
  # Default settings
  default_variation: "nominal"
  
  # Available systematic variations (if applicable)
  variations:
    - "nominal"
    # Add other variations as needed (JES, JER, etc.)

# Utility functions for path construction
path_utils:
  # Example usage: get_sample_path("qcd_data_sideband", run_number=123)
  # Returns: /storage/9/abal/CASE/VAE_results/events/run_123/qcd_data_sideband_RECO.h5
  sample_path_template: "{root_dir}/{sample_name}{suffix}{extension}"